#version 450

layout (location = 0) uniform uvec2 size;

layout (std430, binding = 0) buffer FACTOR {
	float factor[];
};

layout (std430, binding = 1) buffer RESULT {
	float result[];
};

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
	uint x = gl_GlobalInvocationID.x;
	uint y = gl_GlobalInvocationID.y; 
	uint index = y * size.x + x;
	
	result[index] = result[index] * (factor[index] * 0.2f + 0.8f);
}